openapi: 3.0.0
info:
  title: IBM Watson Speech to Text
  description: Transcribe audio into text with speaker labels for interviews.
  version: 1.0.0
servers:
  - url: https://api.us-south.speech-to-text.watson.cloud.ibm.com/instances/c6178b34-fc62-4527-91cf-4f498faff0e4
    description: Hackathon STT Instance
security:
  - BasicAuth: []
paths:
  /v1/recognize:
    post:
      summary: Transcribe Audio
      operationId: recognizeAudio
      parameters:
        - name: model
          in: query
          description: Model to use (e.g., en-US_BroadbandModel).
          required: false
          schema:
            type: string
            default: en-US_Multimedia
        - name: speaker_labels
          in: query
          description: Must be true to distinguish Interviewer from Candidate.
          required: true
          schema:
            type: boolean
            default: true
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Successful transcription
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                  speaker_labels:
                    type: array
                    items:
                      type: object
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
